-- mitori database schema
-- Supabase project: mitori (gvwewkzwwzuvacbldxae)
-- Exported from live database. Not a migration history — a snapshot of current structure.

-- ============================================================
-- context
-- ============================================================
CREATE TABLE public.context (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    "Description" text
);

COMMENT ON TABLE public.context IS 'Tagging system for where or in what situation vocabulary was encountered';

ALTER TABLE public.context ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.context FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- kanji
-- ============================================================
CREATE TABLE public.kanji (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    jlpt text,
    grade text,
    kanjimap_url text,
    kanjigraph_url text,
    meanings text[]
);

COMMENT ON TABLE public.kanji IS 'Individual kanji extracted from words.';

CREATE INDEX idx_kanji_grade ON public.kanji (grade);
CREATE INDEX idx_kanji_jlpt ON public.kanji (jlpt);

ALTER TABLE public.kanji ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.kanji FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- kotoba (core vocabulary; formerly "words")
-- ============================================================
CREATE TABLE public.kotoba (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    context_id bigint REFERENCES public.context(id),
    reading text,
    part_of_speech text DEFAULT 'noun'::text,
    updated_at timestamp with time zone DEFAULT now(),
    has_kanji boolean DEFAULT true,
    meanings text[] NOT NULL,
    sub_part_of_speech text
);

COMMENT ON TABLE public.kotoba IS 'Core vocabulary table.';

CREATE INDEX idx_kotoba_context_id ON public.kotoba (context_id);
CREATE INDEX idx_kotoba_part_of_speech ON public.kotoba (part_of_speech);
CREATE INDEX idx_kotoba_sub_part_of_speech ON public.kotoba (sub_part_of_speech);
CREATE INDEX idx_kotoba_has_kanji ON public.kotoba (has_kanji);

ALTER TABLE public.kotoba ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.kotoba FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- word_kanji (many-to-many: kotoba <-> kanji)
-- ============================================================
CREATE TABLE public.word_kanji (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id bigint REFERENCES public.kotoba(id),
    kanji_id bigint REFERENCES public.kanji(id),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    kanji_meaning_in_word text,
    updated_at timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE public.word_kanji IS 'Many-to-many relationship between words and kanji.';

CREATE INDEX idx_word_kanji_word_id ON public.word_kanji (word_id);
CREATE INDEX idx_word_kanji_kanji_id ON public.word_kanji (kanji_id);

ALTER TABLE public.word_kanji ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.word_kanji FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- captures
-- ============================================================
CREATE TABLE public.captures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url character varying,
    context_id bigint REFERENCES public.context(id),
    raw_text text,
    captured_at timestamp with time zone NOT NULL,
    parsed_at timestamp with time zone
);

COMMENT ON TABLE public.captures IS 'Log of photos captured';

CREATE INDEX idx_captures_context_id ON public.captures (context_id);

ALTER TABLE public.captures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.captures FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- sentences
-- ============================================================
CREATE TABLE public.sentences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence text,
    meaning text,
    reading text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    word_id bigint REFERENCES public.kotoba(id)
);

COMMENT ON TABLE public.sentences IS 'Phrases and sentences captured from photos, like 熊に注意 or ここで喫煙しないでください.';

CREATE INDEX idx_sentences_word_id ON public.sentences (word_id);

ALTER TABLE public.sentences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.sentences FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- Notes
-- ============================================================
-- Single-user app: RLS is enabled on every table with one open policy per
-- table ("allow all - anon") granting full SELECT/INSERT/UPDATE/DELETE to
-- the anon and authenticated roles. There is no user_id column anywhere and
-- no per-row ownership — access control is just "has the Supabase API key",
-- not per-user. If this ever becomes multi-user, these policies and the
-- schema (user_id columns) both need revisiting.
