-- mitori database schema
-- Supabase project: mitori (gvwewkzwwzuvacbldxae)
-- Exported from live database. Not a migration history — a snapshot of current structure.

-- ============================================================
-- kanji
-- ============================================================
CREATE TABLE public.kanji (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    jlpt text,
    grade text,
    kanjimap_url text,
    kanjigraph_url text,
    meanings text[],
    cluster text,
    learned boolean NOT NULL DEFAULT false
);

COMMENT ON TABLE public.kanji IS 'Individual kanji extracted from words.';

CREATE INDEX idx_kanji_grade ON public.kanji (grade);
CREATE INDEX idx_kanji_jlpt ON public.kanji (jlpt);
CREATE INDEX idx_kanji_cluster ON public.kanji (cluster);

ALTER TABLE public.kanji ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.kanji FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- source
-- ============================================================
-- Specific real-world place a kotoba word was actually encountered
-- (e.g. "Uniqlo", "Google Maps", "7-Eleven") — the encounter record, as
-- opposed to category, which is the syllabus grouping of the meaning.
CREATE TABLE public.source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    url text,
    category_id bigint REFERENCES public.category(id),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.source IS 'Specific real-world place a kotoba word was actually encountered (e.g. a named website, app, or store), the encounter record rather than the syllabus grouping.';


ALTER TABLE public.source ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.source FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- language
-- ============================================================
-- Every language the app supports. The flags drive which columns and filters
-- the UI shows, so adding a language is a row here plus content rather than a
-- hunt through hardcoded conditionals. kotoba/sentences/grammar_point/
-- resource/resource_channel.language are foreign keys onto code.
CREATE TABLE public.language (
    code text PRIMARY KEY,
    name text NOT NULL,
    script text NOT NULL,
    direction text NOT NULL DEFAULT 'ltr' CHECK (direction IN ('ltr', 'rtl')),
    level_system text,
    has_reading boolean NOT NULL DEFAULT false,
    has_gender boolean NOT NULL DEFAULT false,
    has_characters boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Seeded: ja (japanese/jlpt), de (latin/cefr), zh (han/hsk).

ALTER TABLE public.language ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.language FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- category
-- ============================================================
-- Hierarchical vocabulary syllabus, two levels deep. Sits on concept rather
-- than kotoba because "apple is a fruit" holds in every language, whereas
-- "I saw this word at a Family Mart" is one encounter in one language — that
-- stays on kotoba.source_id. kind separates core categories (the objects and
-- ideas: chair, apple) from situational ones (the transaction vocabulary you
-- need in a place: bill, fitting room, residence card).
CREATE TABLE public.category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    parent_id bigint REFERENCES public.category(id),
    kind text NOT NULL CHECK (kind IN ('core', 'situational')),
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX idx_category_parent_id ON public.category (parent_id);
CREATE INDEX idx_category_kind ON public.category (kind);

ALTER TABLE public.category ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.category FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- concept
-- ============================================================
-- Language-agnostic meaning shared across languages ("chair", "teacher").
-- A kotoba row is one language's realization of a concept.
CREATE TABLE public.concept (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gloss text NOT NULL UNIQUE,
    part_of_speech text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    slug text UNIQUE,
    category_id bigint REFERENCES public.category(id),
    tier integer CHECK (tier BETWEEN 1 AND 3)
);

COMMENT ON TABLE public.concept IS 'Language-agnostic meaning shared across languages (e.g. "chair", "teacher"). A kotoba row is one language''s realization of a concept; concept_id is nullable because not every word maps cleanly across languages.';
COMMENT ON COLUMN public.concept.slug IS 'Stable syllabus identifier. NULL means the concept predates the syllabus and was not folded into it.';
COMMENT ON COLUMN public.concept.tier IS 'Study priority 1-3, so 1700+ concepts can be worked in a sensible order.';

CREATE INDEX idx_concept_category_id ON public.concept (category_id);
CREATE INDEX idx_concept_tier ON public.concept (tier);

ALTER TABLE public.concept ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.concept FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- kotoba (core vocabulary; formerly "words")
-- ============================================================
CREATE TABLE public.kotoba (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word character varying NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
    reading text,
    part_of_speech text DEFAULT 'noun'::text,
    updated_at timestamp with time zone DEFAULT now(),
    meanings text[] NOT NULL,
    sub_part_of_speech text,
    source_id bigint REFERENCES public.source(id),
    kana_type text CHECK (kana_type IN ('kanji', 'hiragana', 'katakana')),
    learned boolean NOT NULL DEFAULT false,
    language text NOT NULL DEFAULT 'ja' REFERENCES public.language(code),
    concept_id bigint REFERENCES public.concept(id),
    gender text CHECK (gender IN ('der', 'die', 'das')),
    plural text,
    level text,
    CONSTRAINT kotoba_kana_type_required_for_ja
        CHECK (language <> 'ja' OR kana_type IS NOT NULL),
    CONSTRAINT kotoba_gendered_fields_only_for_de
        CHECK (language = 'de' OR (gender IS NULL AND plural IS NULL))
);

COMMENT ON TABLE public.kotoba IS 'Core vocabulary table. One row per word per language.';

CREATE INDEX idx_kotoba_part_of_speech ON public.kotoba (part_of_speech);
CREATE INDEX idx_kotoba_sub_part_of_speech ON public.kotoba (sub_part_of_speech);
CREATE INDEX idx_kotoba_kana_type ON public.kotoba (kana_type);
CREATE INDEX idx_kotoba_source_id ON public.kotoba (source_id);
CREATE INDEX idx_kotoba_language ON public.kotoba (language);
CREATE INDEX idx_kotoba_concept_id ON public.kotoba (concept_id);
CREATE INDEX idx_kotoba_level ON public.kotoba (level);

ALTER TABLE public.kotoba ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.kotoba FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- word_kanji (many-to-many: kotoba <-> kanji)
-- ============================================================
CREATE TABLE public.word_kanji (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id bigint REFERENCES public.kotoba(id),
    kanji_id bigint REFERENCES public.kanji(id),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    kanji_meaning_in_word text,
    updated_at timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE public.word_kanji IS 'Many-to-many relationship between words and kanji.';

CREATE INDEX idx_word_kanji_word_id ON public.word_kanji (word_id);
CREATE INDEX idx_word_kanji_kanji_id ON public.word_kanji (kanji_id);

ALTER TABLE public.word_kanji ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.word_kanji FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- captures
-- ============================================================
CREATE TABLE public.captures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url character varying,
    raw_text text,
    captured_at timestamp with time zone NOT NULL,
    parsed_at timestamp with time zone
);

COMMENT ON TABLE public.captures IS 'Log of photos captured';


ALTER TABLE public.captures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.captures FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- sentences
-- ============================================================
CREATE TABLE public.sentences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence text,
    meaning text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    word_id bigint REFERENCES public.kotoba(id),
    category_id bigint REFERENCES public.category(id),
    language text NOT NULL DEFAULT 'ja' REFERENCES public.language(code)
);

COMMENT ON TABLE public.sentences IS 'Phrases and sentences captured from photos, like 熊に注意 or ここで喫煙しないでください.';

CREATE INDEX idx_sentences_word_id ON public.sentences (word_id);
CREATE INDEX idx_sentences_language ON public.sentences (language);

ALTER TABLE public.sentences ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.sentences FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- sentence_kotoba (many-to-many: sentences <-> kotoba)
-- ============================================================
CREATE TABLE public.sentence_kotoba (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence_id bigint NOT NULL REFERENCES public.sentences(id),
    kotoba_id bigint NOT NULL REFERENCES public.kotoba(id),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    UNIQUE (sentence_id, kotoba_id)
);

COMMENT ON TABLE public.sentence_kotoba IS 'Every kotoba word actually used in a given sentence (not just the single word the sentence was originally written to demonstrate, via sentences.word_id).';

CREATE INDEX idx_sentence_kotoba_sentence_id ON public.sentence_kotoba (sentence_id);
CREATE INDEX idx_sentence_kotoba_kotoba_id ON public.sentence_kotoba (kotoba_id);

ALTER TABLE public.sentence_kotoba ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.sentence_kotoba FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- grammar_point
-- ============================================================
CREATE TABLE public.grammar_point (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    title text NOT NULL,
    category text NOT NULL,
    folder_order integer NOT NULL,
    sort_order integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    language text NOT NULL DEFAULT 'ja' REFERENCES public.language(code)
);

COMMENT ON TABLE public.grammar_point IS 'Grammar point notes (particles, verb forms, patterns, etc.), imported from markdown files in grammar/. slug is the frontmatter id (e.g. "1-particle/1a-は"), content is the markdown body.';

CREATE INDEX idx_grammar_point_category ON public.grammar_point (category);
CREATE INDEX idx_grammar_point_language ON public.grammar_point (language);

ALTER TABLE public.grammar_point ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.grammar_point FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- resource_channel
-- ============================================================
CREATE TABLE public.resource_channel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform text NOT NULL CHECK (platform IN ('youtube', 'tiktok')),
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    url text,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    language text NOT NULL DEFAULT 'ja' REFERENCES public.language(code)
);

COMMENT ON TABLE public.resource_channel IS 'A YouTube/TikTok channel producing Japanese-learning content, e.g. akane-japanese-class.';

ALTER TABLE public.resource_channel ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.resource_channel FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- resource
-- ============================================================
CREATE TABLE public.resource (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id bigint REFERENCES public.resource_channel(id),
    title text NOT NULL,
    url text NOT NULL UNIQUE,
    category text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    transcript text,
    is_transcript_complete boolean NOT NULL DEFAULT true,
    category_id bigint REFERENCES public.category(id),
    language text NOT NULL DEFAULT 'ja' REFERENCES public.language(code)
);

COMMENT ON TABLE public.resource IS 'A single piece of external learning content (a video) from a resource_channel. category is a free-text content-type label (e.g. listening-practice, shadowing, vocabulary, conversation, tips), no fixed enum, same convention as kanji.cluster. category_id optionally files the video under a syllabus category (e.g. a video about ordering at a restaurant -> Restaurant). transcript is the video''s captions (manual, falling back to auto-generated), cleaned of VTT timing/markup - populated by resources/scripts/fetch_transcripts.py + generate_transcript_sql.py, nullable since not every video has captions available. is_transcript_complete is false when the video''s only available caption track is known to be sparse (e.g. scene-label captions rather than full dialogue, with no denser auto-generated fallback) - a manually-verified flag, not derived from a general heuristic.';

CREATE INDEX idx_resource_channel_id ON public.resource (channel_id);
CREATE INDEX idx_resource_category ON public.resource (category);
CREATE INDEX idx_resource_language ON public.resource (language);
CREATE INDEX idx_resource_channel_language ON public.resource_channel (language);

ALTER TABLE public.resource ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow all - anon" ON public.resource FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- ============================================================
-- Notes
-- ============================================================
-- Single-user app: RLS is enabled on every table with one open policy per
-- table ("allow all - anon") granting full SELECT/INSERT/UPDATE/DELETE to
-- the anon and authenticated roles. There is no user_id column anywhere and
-- no per-row ownership — access control is just "has the Supabase API key",
-- not per-user. If this ever becomes multi-user, these policies and the
-- schema (user_id columns) both need revisiting.
--
-- source is the encounter record: the specific real-world place a word was
-- found ("Uniqlo", uniqlo.com). kotoba.source_id is one-to-one per word, and
-- source.category_id optionally files that source under a syllabus category.
--
-- kotoba.kana_type classifies the word's writing system: 'kanji' if it
-- contains any kanji character (regardless of mixed-in okurigana), else
-- 'katakana' or 'hiragana' for kana-only words. Replaces the old has_kanji
-- boolean. kotoba.reading is NULL for non-kanji words (kana_type != 'kanji'),
-- since the reading would just duplicate word there. It is nullable only so
-- non-Japanese rows can omit it; the kotoba_kana_type_required_for_ja
-- constraint keeps it mandatory for every language='ja' row.
--
-- kotoba.language makes the table multi-language: one row is one language's
-- realization of a word, never a wide row holding several languages. This is
-- deliberate — learned, source_id, sentences.word_id and
-- word_kanji.word_id are all per-language facts (you can know テーブル and not
-- yet know "der Tisch"), so merging languages into one row would either
-- conflate independent state or duplicate every relational column per
-- language. Adding a third language is therefore rows, not columns.
--
-- concept is the thin link tying those per-language rows together: one shared
-- meaning, realized once per language. Backfilled from the existing Japanese
-- vocabulary by lower(trim(meanings[1])), which also merged genuine synonyms
-- onto one concept (持ち帰り / お持ち帰り / テイクアウト all → "takeout"), so a
-- concept may legitimately hold several words in the SAME language, not just
-- one per language. concept_id is nullable because not every word maps
-- cleanly across languages — culturally specific vocabulary (畳, お盆) simply
-- stays single-language rather than getting a forced translation.
--
-- The German vocabulary was seeded from german/vocab/batch-NN.csv via
-- german/generate_german_sql.py, one German word per concept. Those rows are
-- machine-generated reference data, unlike the Japanese rows, which were built
-- from words actually encountered — so a German row inherits its meanings
-- from its Japanese sibling (there was no real encounter to record)
-- and always has source_id NULL and learned false. 82 concepts are
-- deliberately Japanese-only: culturally specific vocabulary (畳, 弁当, 神社),
-- proper names (東京, 九州), counters and function words (一つ, 以上), and
-- polite/humble variants German has no register for (お父さん vs 父). Each
-- carries a note in the CSV explaining why.
--
-- category replaced context entirely. context was conflating two things: the
-- syllabus grouping of a meaning ("bill is restaurant vocabulary", true in
-- every language) and the record of a personal encounter ("I saw 割引 at a
-- Family Mart"). The first is now category on concept; the second was already
-- kotoba.source_id. sentences, resource and source carry their own category_id
-- where the old context_id was, and kotoba dropped its context_id entirely —
-- a word's grouping comes from the concept it realizes.
--
-- concept.slug/tier/category_id came from syllabus/, a curated list of 1733
-- concepts. 1148 existing concepts were rewritten in place and 79 more folded
-- into them (Japanese register variants such as 父親/父 collapsing to one
-- "father"), so no word was orphaned. 260 concepts predate the syllabus and
-- keep slug NULL — Japan-specific vocabulary and abstractions too narrow for a
-- core list. The syllabus CSVs remain the source of truth; syllabus/validate.py
-- checks them and syllabus/upload_syllabus.py stages them for a migration.
--
-- kotoba.level is the single proficiency column; its scale is implied by
-- language.level_system (jlpt / cefr / hsk). The old per-language jlpt and cefr
-- columns are gone. kanji.jlpt is untouched — that table is Japanese by nature.
--
-- sentences, grammar_point, resource and resource_channel each carry their own
-- language column so the app's global language toggle can scope them at the
-- query level. All existing rows defaulted to 'ja'. source deliberately has NO
-- language column: a shop or website is not inherently tied to one language and
-- could hold words in both, so the Source view derives its list from the
-- languages of the words pointing at each source instead.
--
-- concept is the one table the toggle never filters — it exists to compare
-- languages side by side, so scoping it to the active language would defeat it.
--
-- kotoba.gender/plural/cefr are German-only, guarded by the
-- kotoba_german_fields_only_for_de constraint so Japanese rows stay clean.
-- jlpt and cefr are deliberately separate columns rather than one generic
-- "level": they are different scales, and kotoba.jlpt is referenced in ~50
-- places across the app that all mean the Japanese scale specifically.
--
-- sentences.category_id is assigned per sentence rather than inherited from
-- the word: one word can have example sentences set in different situations
-- (予約 in a Restaurant and again in Travel).
--
-- sentence_kotoba is a further refinement of sentences.word_id: word_id is
-- the single word a sentence was originally written to demonstrate, but a
-- sentence often incidentally uses several other vocabulary words too (e.g.
-- "会社の利益が増加した。" uses 会社, 利益, and 増加). sentence_kotoba records
-- every kotoba word genuinely present in a sentence (including its own
-- word_id), letting the UI show a sentence's full vocabulary breakdown by
-- part of speech instead of just its one primary word.
--
-- kanji.cluster is a free-text thematic grouping independent of grade/JLPT,
-- e.g. 一/二/三 belong to cluster 'number'. Nullable, plain text (no fixed
-- enum), same convention as kotoba.jlpt/grade.
--
-- resource_channel/resource is a reference library of external learning
-- content (YouTube/TikTok videos), imported from resources/youtube/ via
-- resources/scripts/export_resources.py + generate_seed_sql.py. It mirrors
-- the source/kotoba shape: resource_channel is the general source (a
-- channel), resource is the individual item (a video), and resource.
-- category_id optionally files a resource under the same syllabus category
-- tree as concepts and sentences. Unlike kotoba/sentences, these tables aren't
-- vocabulary data — resource.category is a content-type label (listening-
-- practice, shadowing, vocabulary, conversation, tips), not a grammar/word
-- classification. Extracting actual vocabulary/sentences out of these
-- videos into kotoba/sentences is a separate, not-yet-built pipeline.
